- .vscode/settings.json
https://praha-inc.slack.com/archives/C05AA4932KW/p1688695255808719
なんかもっといいやりかたあったら教えてほしいです:bow:
> [feature] vscode用の設定ファイルを置いた

- package.json
- pnpm-lock.yaml
- src/app/_libs/db/index.ts
- src/app/_libs/env/index.ts
close: #49 
D1にdrizzleで接続できるようにしました。
開発中は[cf-bindings-proxy](https://github.com/james-elicx/cf-bindings-proxy)でローカルのDBを見るようになってます。
ローカルで開発する時は`pnpm run dev`, `pnpm run dev:proxy`の2つを起動するようにお願いします。
> [feature] Make it possible to connect to CloudflareD1 from the server side

- package.json
- pnpm-lock.yaml
- src/app/_components/sheet/index.ts
- src/app/_components/sheet/sheet-close.tsx
- src/app/_components/sheet/sheet-content.tsx
- src/app/_components/sheet/sheet-description.tsx
- src/app/_components/sheet/sheet-title.tsx
- src/app/_components/sheet/sheet-trigger.tsx
- src/app/_components/sheet/sheet.css.ts
- src/app/_components/sheet/sheet.stories.tsx
- src/app/_components/sheet/sheet.tsx
- src/app/_icons/close.svg
- src/app/_theme/dark.css.ts
- src/app/_theme/light.css.ts
- src/app/_theme/theme.css.ts
シートを表示するコンポーネントを実装しました。
また、textMutedの彩度が少し低かったため、高めの値に調整しています。
> [feature] Add a sheet component

- package.json
- pnpm-lock.yaml
Downgrade because it will not be able to connect to D1.
https://github.com/cloudflare/workers-sdk/issues/3756
> [deps] Update dependency wrangler to v3.4.0

- src/app/(main)/(home)/layout.tsx
- src/app/(main)/_components/global-navigation/global-navigation.tsx
- src/app/(main)/shuffle/@posts/_actions/fetch-posts.tsx
- src/app/(main)/shuffle/@posts/page.tsx
- src/app/(main)/shuffle/layout.css.ts
- src/app/(main)/shuffle/layout.tsx
- src/app/(main)/shuffle/page.tsx
- src/app/_icons/shuffle.svg
- src/app/layout.tsx
> [feature] Add a shuffle post list page

- src/app/(main)/_components/github-login-button/github-login-button.css.ts
- src/app/(main)/_components/github-login-button/github-login-button.stories.tsx
- src/app/(main)/_components/github-login-button/github-login-button.tsx
- src/app/(main)/_components/github-login-button/index.ts
- src/app/(main)/_components/header/header-presenter.tsx
- src/app/(main)/_components/login-button/index.ts
- src/app/(main)/_components/login-button/login-button.css.ts
- src/app/(main)/_components/login-button/login-button.tsx
ボタンのスタイルだけ作りました
「Login」ボタン押したらダイアログが開いて、そのダイアログの中にこのボタンが表示される予定です（ダイアログとかそのへんは[ここ](https://github.com/looks-to-me/looks-to-me/pull/215/files)で作っている）
https://praha-inc.slack.com/archives/C05AA4932KW/p1691133347157919?thread_ts=1691098431.124559&cid=C05AA4932KW
> [feature] ログインボタンをgithubっぽいスタイルにした

- README.md
> [feature] [fix] Corrected setup procedure in README

- src/app/(main)/posts/new/_components/input-image-with-preview/input-image-with-preview.tsx
- src/app/(main)/posts/new/_components/post-create-form/post-create-form.tsx
- src/app/_libs/env/index.ts
- src/app/_libs/storage/index.ts
- wrangler.toml
fixes: #59, #60
実際に画像をR2にアップロードできるようにした
- User周りがDBにデータがないと動かないのでプレビューでは動作確認できてない
> [feature] 画像を実際にアップロードする処理を追加

- app/src/app/(main)/posts/new/_components/input-image-with-preview/input-image-with-preview.css.ts
- app/src/app/(main)/posts/new/_components/input-image-with-preview/input-image-with-preview.tsx
/posts/newで大きな画像を入れたときに表示が崩れるのを直しました！
> [bugfix] fix overflow when selecting large images.

- app/src/app/(main)/[atUserName]/(profile)/@header/page.css.ts
- app/src/app/(main)/[atUserName]/(profile)/@header/page.tsx
- app/src/app/(main)/[atUserName]/(profile)/@posts/_actions/fetch-user-posts.tsx
- app/src/app/(main)/[atUserName]/(profile)/@posts/page.css.ts
- app/src/app/(main)/[atUserName]/(profile)/@posts/page.tsx
- app/src/app/(main)/[atUserName]/(profile)/_components/user-summary/user-summary.tsx
- app/src/app/(main)/[atUserName]/(profile)/layout.css.ts
- app/src/app/(main)/[atUserName]/(profile)/layout.tsx
- app/src/app/(main)/[atUserName]/(profile)/page.tsx
- app/src/app/(main)/_repositories/post-repository.ts
- Split user profile page for parallel routes
- Show user profile
- Show user posts
比較用（投稿詳細ページ）
> [feature] feature/user profile page details

- app/src/app/(main)/images/posts/[id]/raw/route.ts
This reverts commit bac0dbc8fdc20a9b07731276979a3af7b86945c1.
> [bugfix] Revert back to cache control due to errors in Cloudflare Images

- app/src/app/(main)/[atUserName]/posts/[postId]/@header/page.tsx
- app/src/app/(main)/images/posts/[id]/raw/route.ts
> Production Release

- apps/web/drizzle.config.ts
> [feature] Fix path to db schema

- apps/web/src/app/_libs/database/schema/tables/images.ts
- apps/web/src/app/_libs/database/schema/tables/post-tags.ts
- apps/web/src/app/_libs/database/schema/tables/posts.ts
- apps/web/src/app/_libs/database/schema/tables/tags.ts
- apps/web/src/app/_libs/database/schema/tables/user-profiles.ts
- apps/web/src/app/_libs/database/schema/tables/user-providers.ts
- apps/web/src/app/_libs/database/schema/tables/users.ts
> [refactor] Delete unused schema types

- apps/web/migrations/0009_tiresome_shockwave.sql
- apps/web/migrations/meta/0009_snapshot.json
- apps/web/migrations/meta/_journal.json
- apps/web/src/app/_libs/database/helpers/index.ts
- apps/web/src/app/_libs/database/schema/index.ts
- apps/web/src/app/_libs/database/schema/tables/mute-users.ts
- apps/web/src/app/_libs/database/schema/tables/users.ts
> Add mute user table

- .github/workflows/pr-push-check.yml
- .github/workflows/publish.yml
- ジョブの名前が間違っていたのを修正
- publishワークフローにタイムアウト時間を追加
- close #597
> Add timeout 10 minutes to CD pipeline & Fix typo

- apps/web/src/app/(main)/new/_components/post-create-form/actions/submit-post.ts
- getLoginUserを使っていない箇所があったので修正
> Refactor submitPost function to use getLoginUser

- apps/web/src/app/(main)/[atUserName]/(details)/@profile/page.tsx
> Fix so that you can't mute when on your own profile page.

- apps/web/src/app/(main)/[atUserName]/(details)/layout.tsx
- apps/web/src/queries/user/get-is-muted-user-by-name.test.ts
- apps/web/src/queries/user/get-is-muted-user-by-name.ts
- ミュートしているときだけバナーが表示されるようにした
close #11
> Fixed banner to be displayed only when muted

- apps/web/migrations/0010_material_naoko.sql
- apps/web/migrations/meta/0010_snapshot.json
- apps/web/migrations/meta/_journal.json
- apps/web/src/app/_libs/database/schema/index.ts
- apps/web/src/app/_libs/database/schema/tables/post-copy.ts
> Add post copy table
